server:
  servlet:
    context-path: /demo/
  port: 9000

management:
  port: 9001
  address: 127.0.0.1

spring:
    maxplus1:
      druid: # 公共属性
        driver-class-name: org.h2.Driver
        data-sources: # 数据源个性化配置
          master: # 注册的DataSource名字为：masterDataSource
            username: h2-master
            password: m123
            url: jdbc:h2:mem:master
            schema: classpath:db/master/schema.sql
            data: classpath:db/master/data.sql
          slave:
            username: h2-slave
            password: s123
            url: jdbc:h2:mem:slave
            schema: classpath:db/slave/schema.sql
            data: classpath:db/slave/data.sql
      mybatis: # 公共属性
          type-aliases-package: com.maxplus1.demo.data.entity
          configuration:
              map-underscore-to-camel-case: true
              default-fetch-size: 100
              default-statement-timeout: 30
          data-sources:
            master: # 数据源+MyBatis个性化配置。默认第一个是主数据源，即@Primary
              mapper-locations: classpath:mapper/master/*.xml # 可以输入数组
              base-package: com.maxplus1.demo.data.dao.master
            slave: # 数据源+MyBatis个性化配置
              mapper-locations: classpath:mapper/slave/*.xml # 可以输入数组
              base-package: com.maxplus1.demo.data.dao.slave